config/routes.rb
Rails.application.routes.draw do
  resources :calculations, only: :create

  root 'calculator#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  before_create :calculate

  enum operation: [
    :sum_op,
    :difference_op,
    :multiplication_op,
    :division_op
  ]

  validates(
    :result,
    numericality: true,
    if: proc { |c| c.result.present? }
  )

  validates(
    :first_input,
    :second_input,
    :request_count,
    numericality: {
      only_integer: true,
      less_than: 100,
      greater_than_or_equal_to: 0
    }
  )

  protected

  def calculate
    self.result = eval "#{Float(first_input)} #{operator} #{Integer(second_input)}" # prevent sql injection
    raise "Invalid result: #{result}" if result.nan? || result.infinite?
  rescue => e
    self.result = nil # override previous result
    self.result_error = e
  ensure
    return result
  end

  def operator
    case operation.to_sym
    when :sum_op then '+'
    when :difference_op then '-'
    when :multiplication_op then '*'
    when :division_op then '/'
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: %i[ show edit update destroy ]

  # GET /calculations or /calculations.json
  def index
    @calculations = Calculation.all
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new

  end

  # POST /calculations or /calculations.json
  def create
    @calculation = Calculation.find_or_initialize_by(calculation_params)

    @calculation.request_count =+ 1
    @calculation.save
  rescue

  end

  # DELETE /calculations/1 or /calculations/1.json
  def destroy
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to calculations_url, notice: "Calculation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calculation_params
      params.require(:calculation).permit(:first_input, :second_input, :operation)
    end
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculations/_form.html.erb
<%= form_with(model: calculation) do |form| %>
  <% if calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calculation.errors.count, "error") %> prohibited this calculation from being saved:</h2>

      <ul>
        <% calculation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_input %>
    <%= form.number_field :first_input %>
  </div>

  <div class="field">
    <%= form.label :operation %>
    <%= form.number_field :operation %>
  </div>

  <div class="field">
    <%= form.label :second_input %>
    <%= form.number_field :second_input %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calculations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calculations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">Expression</th>
      <th>Anwser</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @calculations.each do |calculation| %>
      <tr>
        <td><%= calculation.first_input %></td>
        <td><%= calculation.operation %></td>
        <td><%= calculation.second_input %></td>
        <td><%= calculation.result %></td>
        <td><%= link_to 'Destroy', calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calculation', new_calculation_path %>

app/views/calculations/new.html.erb
<h1>New Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Back', calculations_path %>

app/views/calculator/index.html.erb
<h1 class="text-center">Calculator</h1>
<hr/>
<div style="width: 100%; margin: 0 auto;">
  <%= react_component('Calculator') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>RCS</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>